/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Matta Morales
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    String almacenado = "";
    String almacenado2;
    String operacion = "0";
    float resultado;
    float porcentaje;
    boolean concatenacion = false;
    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_resultado = new javax.swing.JLabel();
        btn_M1 = new javax.swing.JButton();
        btn_masmenos = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_MC5 = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_CE = new javax.swing.JButton();
        btn_MR = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_mc = new javax.swing.JButton();
        btn_MS = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_M2 = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_MOD = new javax.swing.JButton();
        btn_porcentaje = new javax.swing.JButton();
        btn_coma = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        lbl_concatenacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        lbl_resultado.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_resultado.setText("0");
        lbl_resultado.setToolTipText("");
        lbl_resultado.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        btn_M1.setText("M+");

        btn_masmenos.setText("±");
        btn_masmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masmenosActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_MC5.setText("BS");

        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        btn_CE.setText("CE");

        btn_MR.setText("MR");

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_mc.setText("MC");
        btn_mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mcActionPerformed(evt);
            }
        });

        btn_MS.setText("MS");

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_multiplicacion.setText("*");
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });

        btn_M2.setText("M-");

        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_MOD.setText("MOD");

        btn_porcentaje.setText("%");
        btn_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcentajeActionPerformed(evt);
            }
        });

        btn_coma.setText(",");
        btn_coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comaActionPerformed(evt);
            }
        });

        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        lbl_concatenacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_MC5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_masmenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_M2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_coma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_MOD))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_concatenacion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_0, btn_1, btn_2, btn_3, btn_4, btn_5, btn_6, btn_7, btn_8, btn_9, btn_coma});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_MOD, btn_division, btn_igual, btn_multiplicacion, btn_porcentaje, btn_resta, btn_suma});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_C, btn_CE, btn_M1, btn_M2, btn_MC5, btn_MR, btn_MS, btn_masmenos, btn_mc});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_concatenacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_MOD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_multiplicacion)
                            .addComponent(btn_porcentaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_M1)
                                .addComponent(btn_M2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_MS)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_MR)
                                    .addComponent(btn_mc))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_MC5)
                            .addComponent(btn_C)
                            .addComponent(btn_CE)
                            .addComponent(btn_masmenos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_9)
                                    .addComponent(btn_8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_6)
                                    .addComponent(btn_5)
                                    .addComponent(btn_4))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_1)
                                    .addComponent(btn_2)
                                    .addComponent(btn_3))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_coma)
                                    .addComponent(btn_0))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_0, btn_1, btn_2, btn_3, btn_4, btn_5, btn_6, btn_7, btn_8, btn_9, btn_coma});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_MOD, btn_division, btn_multiplicacion, btn_porcentaje, btn_resta, btn_suma});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed

    if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "7");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("7");
        almacenado = "7";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"7");
    almacenado = almacenado + "7";
    }
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "8");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("8");
        almacenado = "8";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"8");
    almacenado = almacenado + "8";
    }
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "9");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("9");
        almacenado = "9";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"9");
    almacenado = almacenado + "9";
    }
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "4");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("4");
        almacenado = "4";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"4");
    almacenado = almacenado + "4";
    }
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "5");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("5");
        almacenado = "5";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"5");
    almacenado = almacenado + "5";
    }
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "6");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("6");
        almacenado = "6";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"6");
    almacenado = almacenado + "6";
    }
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "3");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("3");
        almacenado = "3";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"3");
    almacenado = almacenado + "3";
    }
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
         lbl_resultado.setText("0");
     }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "2");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("2");
        almacenado = "2";
    }
    else{    
    lbl_resultado.setText(lbl_resultado.getText() +"2");
    almacenado = almacenado + "2";
    }
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "1");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("1");
         almacenado = "1";
    }else{    
    lbl_resultado.setText(lbl_resultado.getText() +"1");
    almacenado = almacenado + "1";
    }
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
     if(almacenado.length()==0&&concatenacion == true){
        lbl_resultado.setText("0");
    }
    lbl_concatenacion.setText(lbl_concatenacion.getText() + "0");
    if(lbl_resultado.getText().equals("0")){
        lbl_resultado.setText("0");
         almacenado = lbl_resultado.getText();
    }else{    
    lbl_resultado.setText(lbl_resultado.getText()+"0");
    almacenado = almacenado + "0";
    }
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
    almacenado = "";
    almacenado2 = "";
    operacion = "0";
    resultado = 0;
    concatenacion = false;
    lbl_resultado.setText("0");
    lbl_concatenacion.setText("");
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
   try{
        if('*'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)){
        lbl_concatenacion.setText(lbl_concatenacion.getText() + "*");
    }
    } catch(java.lang.StringIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "No se pueden identificar los parámetros necesarios");
    }
    if(!"0".equals(operacion)){
    this.btn_igualActionPerformed(evt);
    almacenado = "";
    lbl_resultado.setText(String.valueOf(resultado));
    concatenacion = true;
    operacion = "*";   
    }else{
         if(concatenacion==true){
        operacion = "*";
        almacenado = "";
        lbl_resultado.setText("0");
        }else{
        almacenado2 = almacenado;
        almacenado = "";
        lbl_resultado.setText("0");
        operacion = "*";
        }
    }
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        switch (operacion) {
            case "*":
                resultado = Float.parseFloat(almacenado2)*Float.parseFloat(almacenado);
                lbl_resultado.setText(String.valueOf(resultado));
                almacenado2 = String.valueOf(resultado);
                operacion = "0";
                concatenacion = true;
                break;
            case "+":
                resultado = Float.parseFloat(almacenado2)+Float.parseFloat(almacenado);
                lbl_resultado.setText(String.valueOf(resultado));
                almacenado2 = String.valueOf(resultado);
                operacion = "0";
                concatenacion = true;
                break;
            case "-":
                resultado = Float.parseFloat(almacenado2)-Float.parseFloat(almacenado);
                lbl_resultado.setText(String.valueOf(resultado));
                almacenado2 = String.valueOf(resultado);
                operacion = "0";
                concatenacion = true;
                break;
            case"/":
                resultado = Float.parseFloat(almacenado2)/Float.parseFloat(almacenado);
                lbl_resultado.setText(String.valueOf(resultado));
                almacenado2 = String.valueOf(resultado);
                operacion = "0";
                concatenacion = true;
                break;
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
   try{
        if('+'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)){
        lbl_concatenacion.setText(lbl_concatenacion.getText() + "+");
    }
    } catch(java.lang.StringIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "No se pueden identificar los parámetros necesarios");
    }
    if(!"0".equals(operacion)){
    this.btn_igualActionPerformed(evt);
    almacenado = "";
    lbl_resultado.setText(String.valueOf(resultado));
    concatenacion = true;
    operacion = "+";   
    }else{
        if(concatenacion==true){
        operacion = "+";
        almacenado = "";
        lbl_resultado.setText("0");
        }else{
        almacenado2 = almacenado;
        almacenado = "";
        lbl_resultado.setText("0");
        operacion = "+";
        }
    }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
    try{
        if('-'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)){
        lbl_concatenacion.setText(lbl_concatenacion.getText() + "-");
    }
    } catch(java.lang.StringIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "No se pueden identificar los parámetros necesarios");
    } 
    if(!"0".equals(operacion)){
    this.btn_igualActionPerformed(evt);
    almacenado = "";
    lbl_resultado.setText(String.valueOf(resultado));
    concatenacion = true;
    operacion = "-";   
    }else{
         if(concatenacion==true){
        operacion = "-";
        almacenado = "";
        lbl_resultado.setText("0");
        }else{
        almacenado2 = almacenado;
        almacenado = "";
        lbl_resultado.setText("0");
        operacion = "-";
        }
    }
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
    try{
        if('/'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)){
        lbl_concatenacion.setText(lbl_concatenacion.getText() + "/");
    }
    } catch(java.lang.StringIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "No se pueden identificar los parámetros necesarios");
    }
    if(!"0".equals(operacion)){
    this.btn_igualActionPerformed(evt);
    almacenado = "";
    lbl_resultado.setText(String.valueOf(resultado));
    concatenacion = true;
    operacion = "/";   
    }else{
         if(concatenacion==true){
        operacion = "/";
        almacenado = "";
        lbl_resultado.setText("0");
        }else{
        almacenado2 = almacenado;
        almacenado = "";
        lbl_resultado.setText("0");
        operacion = "/";
        }
    }
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mcActionPerformed

    private void btn_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcentajeActionPerformed
   try{ 
        if(Float.parseFloat(almacenado2)>0&&Float.parseFloat(almacenado)<=100&&Float.parseFloat(almacenado)>0){
        porcentaje = Integer.parseInt(almacenado);
      
        switch(operacion){
             case "*":
             almacenado2=(String.valueOf(Float.parseFloat(almacenado2)*(porcentaje*Float.parseFloat(almacenado2)/100)));
             lbl_concatenacion.setText(lbl_concatenacion.getText() + "%");
             lbl_resultado.setText(almacenado2);
             operacion = "0";
             concatenacion = true;
                break;
            case "+":
             almacenado2=(String.valueOf(Float.parseFloat(almacenado2)+(porcentaje*Float.parseFloat(almacenado2)/100)));
             lbl_concatenacion.setText(lbl_concatenacion.getText() + "%");
             lbl_resultado.setText(almacenado2);
             operacion = "0";
             concatenacion = true;
                break;
            case "-":
             almacenado2=(String.valueOf(Float.parseFloat(almacenado2)-(porcentaje*Float.parseFloat(almacenado2)/100)));
             lbl_concatenacion.setText(lbl_concatenacion.getText() + "%");
             lbl_resultado.setText(almacenado2);
             operacion = "0";
             concatenacion = true;
                break;
            case"/":
             almacenado2=(String.valueOf(Float.parseFloat(almacenado2)/(porcentaje*Float.parseFloat(almacenado2)/100)));
             lbl_concatenacion.setText(lbl_concatenacion.getText() + "%");
             lbl_resultado.setText(almacenado2);
             operacion = "0";
             concatenacion = true;
                break;
        }
    }else{
        JOptionPane.showMessageDialog(null, "No se pueden identificar los parámentros necesarios");
    }
   }catch(java.lang.NullPointerException e){
   JOptionPane.showMessageDialog(null, "No se pueden identificar los parámentros necesarios");
   }  
    }//GEN-LAST:event_btn_porcentajeActionPerformed

    private void btn_masmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masmenosActionPerformed

    if(lbl_concatenacion.getText().length()==0){
       lbl_resultado.setText("-");
        almacenado = "-";     
        lbl_concatenacion.setText(lbl_concatenacion.getText() + "-");
    }else if ('-'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)) {
         lbl_resultado.setText("-");
         almacenado = "-";     
         lbl_concatenacion.setText(lbl_concatenacion.getText() + "-");        
         }
    }//GEN-LAST:event_btn_masmenosActionPerformed

    private void btn_comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comaActionPerformed
if(lbl_concatenacion.getText().length()>=1){
  if('.'!=lbl_concatenacion.getText().charAt(lbl_concatenacion.getText().length()-1)&&!almacenado.contains(".")){
     lbl_concatenacion.setText(lbl_concatenacion.getText() + ".");    
     lbl_resultado.setText(lbl_resultado.getText() + ".");
     almacenado = lbl_resultado.getText();
    }
}
    }//GEN-LAST:event_btn_comaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_M1;
    private javax.swing.JButton btn_M2;
    private javax.swing.JButton btn_MC5;
    private javax.swing.JButton btn_MOD;
    private javax.swing.JButton btn_MR;
    private javax.swing.JButton btn_MS;
    private javax.swing.JButton btn_coma;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_masmenos;
    private javax.swing.JButton btn_mc;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_porcentaje;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel lbl_concatenacion;
    private javax.swing.JLabel lbl_resultado;
    // End of variables declaration//GEN-END:variables
}
